[package]
name = "pyreworks-g560-driver"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.3"
nusb = "0.1.10"
pyreworks-common = { version = "0.1.0", path = "../../common" }
thiserror = "1.0.64"
tokio = "1.40.0"
